version: '3.1'

services:

  restapi:
    image: ekravchenko/restapi:latest
    restart: always
    ports:
      - 8082:8000
    volumes:
      - './:/usr/src/app'
    depends_on: 
      - mongo
    container_name: notes-restapi
    environment:
      NOTES_CONNECTION_STRING: 'mongodb://notes-user:sa@mongo:27017/notes?retryWrites=true&w=majority'

  mongo:
    image: ekravchenko/notes-mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    container_name: notes-mongo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    depends_on: 
      - mongo
    container_name: notes-mongo-express